### ISSUE TITLE
Fix measure numbers in exported PDF

### ISSUE THREAD

**Issue by vdye** [bigredbands/rank-panda#13]
The exported PDF assumes all measures are 4 counts, regardless of how it's set up in the application. This creates incorrect measure numbers in the drill PDF for time signatures != 4/4.

Instead, the `PDFGenerator` should use `DrillInfo.getCountsHashMap()` to calculate the correct measure numbers.

**Comment by parker-rho** [comment]
When trying to implement this it seems like the CountsHashMap stays empty while running the program. Where does the CountsHashMap get updated in the code? It seems to be empty even when I change the song constants. Should I implement that feature as well?

**Comment by vdye** [comment]
It should be set based on the "Song Constants" panel that pops up when you first open the program. Those constants are persisted in the `.pnd` file (although, frustratingly, they don't visibly show up in the "Song Constants" panel that pops up when you load the file - I'll open a separate bug for that). If the `CountsHashMap` isn't populated, it's probably because those Song Constants aren't populated either (in which case, just assume 4/4 time).

**Comment by parker-rho** [comment]
Understood. Thank you!
